#!/usr/bin/env python

import sys
from os.path import join, dirname, normpath, abspath

path = abspath(normpath(join(dirname(__file__), 'src')))

sys.path.insert(1, path)

from syncloud.sam.versions import Versions

filename = sys.argv[1]
app = sys.argv[2]
version = sys.argv[3]

versions = Versions(filename)
versions.update(app, version)



